name: Compilar APK y AAB Android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener archivos del proyecto
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Motor Android (Flutter y Licencias)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'

      - name: Aceptar licencias de Android automáticamente
        run: |
          yes | flutter doctor --android-licenses || true

      - name: Configurar requerimientos móviles
        run: |
          echo "certifi" > requirements.txt

      # 1. COMPILAR EL APK CON FLET ESTABLE (0.25.2) PARA TU CELULAR
      - name: Instalar Flet Estable para APK (0.25.2)
        run: |
          pip install flet==0.25.2 certifi

      - name: Construir APK Estable
        run: |
          yes | flet build apk --build-version "1.0.33" --build-number 33 --org com.erwingim --project bitacorafinanciera

      # 2. COMPILAR EL AAB CON FLET MODERNO Y LA SINTAXIS CORRECTA CON IGUAL (=)
      - name: Actualizar a Flet Moderno para AAB (API 36 Nativa)
        run: |
          pip install --upgrade flet certifi

      - name: Construir AAB para Google Play Console
        run: |
          yes | flet build aab --build-version "1.0.33" --build-number 33 --org com.erwingim --project bitacorafinanciera --flutter-build-args="--android-skip-build-dependency-validation"

      - name: Firmar el archivo AAB correctamente para Google Play
        run: |
          AAB_FILE=$(find build/aab -name "*.aab" | head -n 1)
          
          # Limpiar firmas genéricas previas
          zip -d "$AAB_FILE" META-INF/\* || true
          
          # Firmar usando jarsigner con los estándares de Google Play
          jarsigner -verbose \
            -sigalg SHA256withRSA \
            -digestalg SHA-256 \
            -keystore bitacora-key.keystore \
            -storepass bitacora2026 \
            -keypass bitacora2026 \
            "$AAB_FILE" bitacora

      - name: Entregar Archivo AAB Oficial
        uses: actions/upload-artifact@v4
        with:
          name: Bitacora-AAB-Oficial
          path: build/aab/**/*.aab

      - name: Entregar Archivo APK
        uses: actions/upload-artifact@v4
        with:
          name: Bitacora-APK
          path: build/apk/**/*.apk
